development:
  adapter: async

test:
  adapter: test

production:
  adapter: async  # change 20210207 redisから変更

  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: fishing_archive_production
